### ISSUE TITLE
Size doesn't display correctly when text is listed below image

### ISSUE THREAD

**Issue by jpage4500** [rhwood/jsplitbutton#308]
Hi,

I just wanted to report this before I forgot. I wanted to create a drop-down button in a toolbar. 

My current toolbar buttons shows icons primarily with the label listed below -- like this:
<img width="280" alt="image" src="https://github.com/rhwood/jsplitbutton/assets/1895553/4b77086b-6b0d-4a2b-baa6-ac33835a4c6c">

The last item "Custom" is trying to use this library to show a drop-down menu. But, as you can see the button size isn't large enough to cover the image and dropdown arrow.

Is this something I'm doing wrong or is this button just not meant to work this way? If it's an easy fix I can look at making it but wanted to get your $.02 first

```
                Image icon = loadImage("icon_script.png");
                JSplitButton button = new JSplitButton(new ImageIcon(icon));
                button.setText("Custom");
                button.setFont(new Font(Font.SERIF, Font.PLAIN, 10));
                button.setToolTipText("View custom scripts");
                button.setVerticalTextPosition(SwingConstants.BOTTOM);
                button.setHorizontalTextPosition(SwingConstants.CENTER);
                button.setPopupMenu(popup);
                toolbar.add(button);
```

**Comment by jpage4500** [comment]
quick update.. i fixed it (somewhat) but just increasing the size

<img width="77" alt="image" src="https://github.com/rhwood/jsplitbutton/assets/1895553/b61e5c50-46ae-46d3-84f5-4c835b30de06">

```
                Dimension preferredSize = button.getPreferredSize();
                preferredSize.width += 25;
                button.setPreferredSize(preferredSize);
```

**Comment by rhwood** [comment]
I'm considering this a bug, but won't be able to look at it until this weekend.

**Comment by rhwood** [comment]
@jpage4500 
I am struggling to recreate the problem you have (I think I can see it, but I'm not able to definitively replicate it). So I have three questions:
1. What is the `LayoutManager` for the component the button is embedded in?
2. What is the Look and Feel being used?
3. Does this workaround produce acceptable results?
```
Dimension preferredSize = button.getPreferredSize();
preferredSize.width += button.getArrowSize();
button.setPreferredSize(preferredSize);
```

**Comment by jpage4500** [comment]
Sorry for the slow response -- I just tried the latest version and yes that works great. Thanks!

![image](https://github.com/rhwood/jsplitbutton/assets/1895553/0b6ad54f-c491-4c7d-b26b-650e559ce2db)
